### ISSUE TITLE
Can't pip install 

### ISSUE THREAD

**Issue by kingwongf** [convexfi/riskparity.py#11]
#### Problem description

Cannot pip install package. 
#### Example

```
pip install riskparityportfolio
# insert code here ...
```

which returns
```
Collecting riskparityportfolio
  Using cached https://files.pythonhosted.org/packages/4c/b0/d24ca75f3c28a31872d2efd191f2aada634bbf55101675bd5363f3fe6c0d/riskparityportfolio-0.2.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR:   ERROR: Complete output from command /Users/kingf.wong/.conda/envs/FinanceML/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/24/940nh5796kl2kb647xg2_m_00000gn/T/pip-wheel-443i6gz2/quadprog/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/24/940nh5796kl2kb647xg2_m_00000gn/T/pip-wheel-2l5m_62k:
      ERROR: running bdist_wheel
      running build
      running build_ext
      cythoning quadprog/quadprog.pyx to quadprog/quadprog.cpp
      /Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/24/940nh5796kl2kb647xg2_m_00000gn/T/pip-wheel-443i6gz2/quadprog/quadprog/quadprog.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      building 'quadprog' extension
      creating build
      creating build/temp.macosx-10.7-x86_64-3.7
      creating build/temp.macosx-10.7-x86_64-3.7/quadprog
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -Iquadprog -I/Users/kingf.wong/.conda/envs/FinanceML/include/python3.7m -c quadprog/quadprog.cpp -o build/temp.macosx-10.7-x86_64-3.7/quadprog/quadprog.o
      warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
      quadprog/quadprog.cpp:2523:28: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
        __pyx_t_3 = ((__pyx_t_11 != __pyx_v_n1) != 0);
                      ~~~~~~~~~~ ^  ~~~~~~~~~~
      quadprog/quadprog.cpp:2636:28: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
        __pyx_t_3 = ((__pyx_t_11 != __pyx_v_m1) != 0);
                      ~~~~~~~~~~ ^  ~~~~~~~~~~
      3 warnings generated.
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -Iquadprog -I/Users/kingf.wong/.conda/envs/FinanceML/include/python3.7m -c quadprog/aind.c -o build/temp.macosx-10.7-x86_64-3.7/quadprog/aind.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -Iquadprog -I/Users/kingf.wong/.conda/envs/FinanceML/include/python3.7m -c quadprog/solve.QP.c -o build/temp.macosx-10.7-x86_64-3.7/quadprog/solve.QP.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -Iquadprog -I/Users/kingf.wong/.conda/envs/FinanceML/include/python3.7m -c quadprog/util.c -o build/temp.macosx-10.7-x86_64-3.7/quadprog/util.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -Iquadprog -I/Users/kingf.wong/.conda/envs/FinanceML/include/python3.7m -c quadprog/dpofa.c -o build/temp.macosx-10.7-x86_64-3.7/quadprog/dpofa.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -Iquadprog -I/Users/kingf.wong/.conda/envs/FinanceML/include/python3.7m -c quadprog/daxpy.c -o build/temp.macosx-10.7-x86_64-3.7/quadprog/daxpy.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -Iquadprog -I/Users/kingf.wong/.conda/envs/FinanceML/include/python3.7m -c quadprog/ddot.c -o build/temp.macosx-10.7-x86_64-3.7/quadprog/ddot.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -Iquadprog -I/Users/kingf.wong/.conda/envs/FinanceML/include/python3.7m -c quadprog/dscal.c -o build/temp.macosx-10.7-x86_64-3.7/quadprog/dscal.o
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -I/Users/kingf.wong/.conda/envs/FinanceML/include -arch x86_64 -Iquadprog -I/Users/kingf.wong/.conda/envs/FinanceML/include/python3.7m -c quadprog/f2c_lite.c -o build/temp.macosx-10.7-x86_64-3.7/quadprog/f2c_lite.o
      creating build/lib.macosx-10.7-x86_64-3.7
      g++ -bundle -undefined dynamic_lookup -L/Users/kingf.wong/.conda/envs/FinanceML/lib -arch x86_64 -L/Users/kingf.wong/.conda/envs/FinanceML/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/quadprog/quadprog.o build/temp.macosx-10.7-x86_64-3.7/quadprog/aind.o build/temp.macosx-10.7-x86_64-3.7/quadprog/solve.QP.o build/temp.macosx-10.7-x86_64-3.7/quadprog/util.o build/temp.macosx-10.7-x86_64-3.7/quadprog/dpofa.o build/temp.macosx-10.7-x86_64-3.7/quadprog/daxpy.o build/temp.macosx-10.7-x86_64-3.7/quadprog/ddot.o build/temp.macosx-10.7-x86_64-3.7/quadprog/dscal.o build/temp.macosx-10.7-x86_64-3.7/quadprog/f2c_lite.o -o build/lib.macosx-10.7-x86_64-3.7/quadprog.cpython-37m-darwin.so
      clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
      ld: library not found for -lstdc++
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      error: command 'g++' failed with exit status 1
      ----------------------------------------
      ERROR: Failed building wheel for quadprog
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/setuptools/installer.py", line 126, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/Users/kingf.wong/.conda/envs/FinanceML/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/24/940nh5796kl2kb647xg2_m_00000gn/T/tmp7hkzyq3z', '--quiet', 'quadprog']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/24/940nh5796kl2kb647xg2_m_00000gn/T/pip-install-mgb8ijkt/riskparityportfolio/setup.py", line 141, in <module>
        include_package_data=True,
      File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/setuptools/dist.py", line 676, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/pkg_resources/__init__.py", line 766, in resolve
        replace_conflicting=replace_conflicting
      File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1061, in obtain
        return installer(requirement)
      File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/Users/kingf.wong/.conda/envs/FinanceML/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/24/940nh5796kl2kb647xg2_m_00000gn/T/tmp7hkzyq3z', '--quiet', 'quadprog']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/24/940nh5796kl2kb647xg2_m_00000gn/T/pip-install-mgb8ijkt/riskparityportfolio/
```

#### Expected behavior

Expeted to be installed
#### Environment:
- platform (e.g. Linux, OSX, Windows): OSX
- riskparityportfolio version (e.g. 1.1): 0.2
- installation method (e.g. pip, source): pip

**Comment by mirca** [comment]
Hi @kingwongf, I wonder what happened here? thanks!

**Comment by kingwongf** [comment]
Sorry, it's my mistake. I misread the error. It's due to quadprog installation and command tool problems rather than your package. Still trying to get quadprog install.
